export const overviewPageLogo = "//div[@class='app_logo']"
export const paymentInfo = "//div[normalize-space()='Payment Information:']"
export const cardInfo = "(//div[normalize-space()='SauceCard #31337'])[1]"
export const shippingInfo = "//div[normalize-space()='Shipping Information:']"
export const deliveryMsg = "//div[normalize-space()='Free Pony Express Delivery!']"
export const priceInfo = "//div[normalize-space()='Price Total']"
export const subtotalLbale = "//div[@class='summary_subtotal_label']"
export const taxLabel = "//div[@class='summary_tax_label']"
export const totalLabel = "//div[@class='summary_total_label']"
export const finishBtn = "//button[@id='finish']"
export const CancBtn = "//button[@id='cancel']"
export const backPackItemPrice = "//div[@class='inventory_item_price']"