export const shoppCart = "//a[@class='shopping_cart_link']"
export const cartQttLabel = "//div[@class='cart_quantity_label']"
export const cartItem = "//div[@class='cart_item']"
export const cartDescLabel = "//div[@class='cart_desc_label']"
export const cartQtt="//div[@class='cart_quantity']"
export const itemName = "//div[@class='inventory_item_name']"
export const itemPrice = "//div[@class='inventory_item_price']"
export const continueShopBtn= "//button[@id='continue-shopping']"
export const removeBtn = "//button[@id='remove-sauce-labs-backpack']"
export const removeBtnBoltTshirt = "//button[@id='remove-sauce-labs-bolt-t-shirt']"
export const checkoutBtn = "//button[@id='checkout']"