export const landingPageLogo = "//div[@class='app_logo']"
export const backpackImg = "//img[@alt='Sauce Labs Backpack']"
export const backpackTitle = "//div[normalize-space()='Sauce Labs Backpack']"
export const backpackPrice = "//body[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]"
export const backpackaddToCart = "//button[@id='add-to-cart-sauce-labs-backpack']"
export const removebtnBackPack="//button[@id='remove-sauce-labs-backpack']"
export const BikeLightImg = "//img[@alt='Sauce Labs Bike Light']"
export const BikeLightTitle = "//div[normalize-space()='Sauce Labs Bike Light']"
export const BikeLightPrice = "//body/div[@id='root']/div[@id='page_wrapper']/div[@id='contents_wrapper']/div[@id='inventory_container']/div/div[@id='inventory_container']/div[@class='inventory_list']/div[2]/div[2]/div[1]/div[1]"
export const BikeLightaddToCart = "//button[@id='add-to-cart-sauce-labs-bike-light']"
export const BoltTShirtImg = "//img[@alt='Sauce Labs Bolt T-Shirt']"
export const BoltTShirtTitle = "//div[normalize-space()='Sauce Labs Bolt T-Shirt']"
export const BoltTShirtPrice = "//body/div[@id='root']/div[@id='page_wrapper']/div[@id='contents_wrapper']/div[@id='inventory_container']/div/div[@id='inventory_container']/div[@class='inventory_list']/div[2]/div[2]/div[1]/div[1]"
export const BoltTShirtaddToCart = "//button[@id='add-to-cart-sauce-labs-bolt-t-shirt']"
export const FleeceJacketImg = "//img[@alt='Sauce Labs Fleece Jacket']"
export const FleeceJacketTitle = "//div[normalize-space()='Sauce Labs Fleece Jacket']"
export const FleeceJacketPrice = "//body/div[@id='root']/div[@id='page_wrapper']/div[@id='contents_wrapper']/div[@id='inventory_container']/div/div[@id='inventory_container']/div[@class='inventory_list']/div[2]/div[2]/div[1]/div[1]"
export const FleeceJacketaddToCart = "//button[@id='add-to-cart-sauce-labs-fleece-jacket']"
export const OnesieImg = "//img[@alt='Sauce Labs Onesie']"
export const OnesieTitle = "//div[normalize-space()='Sauce Labs Onesie']"
export const OnesiePrice = "//body/div[@id='root']/div[@id='page_wrapper']/div[@id='contents_wrapper']/div[@id='inventory_container']/div/div[@id='inventory_container']/div[@class='inventory_list']/div[2]/div[2]/div[1]/div[1]"
export const OnesieaddToCart = "//button[@id='add-to-cart-sauce-labs-onesie']"
export const TShirtRedImg = "//img[@alt='Test.allTheThings() T-Shirt (Red)']"
export const TShirtRedTitle = "//div[normalize-space()='Test.allTheThings() T-Shirt (Red)']"
export const TShirtRedPrice = "//body/div[@id='root']/div[@id='page_wrapper']/div[@id='contents_wrapper']/div[@id='inventory_container']/div/div[@id='inventory_container']/div[@class='inventory_list']/div[2]/div[2]/div[1]/div[1]"
export const TShirtRedaddToCart = "//button[@id='add-to-cart-test.allthethings()-t-shirt-(red)']"
export const burgermenuBtn = "//button[@id='react-burger-menu-btn']"
export const allItemsLink = "//a[@id='inventory_sidebar_link']"
export const Aboutlink = "//a[@id='about_sidebar_link']"
export const LogoutLink = "//a[@id='logout_sidebar_link']"
export const ResetAppLink = "//a[@id='reset_sidebar_link']"
export const crossBtn= "//button[@id='react-burger-cross-btn']"
export const shoppingCartIcon= "//a[@class='shopping_cart_link']"
export const product_sort_container = "//select[@class='product_sort_container']"
export const inventory_container = "(//div[@id='inventory_container'])[2]"
export const Footer = "//footer[@class='footer']"
export const footerText = "//div[@class='footer_copy']"
export const twitterlink = "//li[@class='social_twitter']"
export const facebooklink = "//a[normalize-space()='Facebook']"
export const LinkedInlink = "//a[normalize-space()='LinkedIn']"
export const listOfItems = "//div[@class='inventory_item']"
export const addAllItemstoCart = 'button.btn.btn_primary.btn_small.btn_inventory'
